# -*- coding: utf-8 -*-
"""conversor_numeroDecimal.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kac5XXIgFafzghoabaXOklB9zIkwvZdc
"""

# Pedir número al usuario
num_decimal = int(input("¡Hola! Ingresa un número decimal: "))

# Identificar si el número ingresado es par o no
if num_decimal % 2 == 0:
    var_par="par"
else:
    var_par="impar"

# Asignar una descripción a un  numero par, como binario y a un impar como octal

if var_par == "par":
    var_des="binario"
else:
    var_des="octal"

# Mostrar el número ingresado
print(f"El número ingresado es {num_decimal}, lo cual corresponde a un número {var_par}.\nDe acuerdo a esto, se van a encontrar los numeros hexadecimal y {var_des}.")

# Convertir a binario, octal y hexadecimal
n_binario = bin(num_decimal)[2:]
n_octal = oct(num_decimal)[2:]
n_hexadecimal = hex(num_decimal)[2:]

# Mostrar resultados
print("\nResultados")
print(f"Hexadecimal: {n_hexadecimal}")

# Condición para mostrar binario o octal según si el número es par o impar
if num_decimal % 2 == 0:
    print(f"Binario: {n_binario}")
else:
    print(f"Octal: {n_octal}")